### ISSUE TITLE
Admonition styling

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-ogc#12]
The WFS FES document has a profusion of Admonitions (cautions); but I've just discovered that we've never assigned rendering to admonitions in the HTML CSS. (We have in the Word CSS.)

I propose to make HTML admonitions pale red, and otherwise identical to the markup of Notes. Once you approve, I will propagate this to the other gems' stylesheets.

**Comment by opoudjis** [comment]
@ronaldtse Please review

[17-069.html.zip](https://github.com/riboseinc/metanorma-ogc/files/2691671/17-069.html.zip)

**Comment by ronaldtse** [comment]
So all the `CAUTION` text in this document are TODOs. Pale red is fine for CAUTIONs, but can we have real TODOs?

**Comment by opoudjis** [comment]
https://github.com/riboseinc/metanorma-iso/issues/148, which is low priority: proposed to render them  in the same way as reviewer comments. Of course, that in turn requires https://github.com/riboseinc/isodoc-style/issues/3 to be done. If you'd rather we not adopt reviewer comments as the mechanism, let me know in https://github.com/riboseinc/metanorma-iso/issues/148.

I am propagating the admonition rendering in HTML CSS to the other gems in the mean time, and deeming this specific ticket closed.
