### ISSUE TITLE
Example captions

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-ogc#13]
Examples in WFS_FES are captioned. There is no provision for title captions in Metanorma to date (because examples are not captioned in ISO), and example captions are currently ignored. @ronaldtse  Are you ok for me to add support for title captions to OGC? And to Metanorma in general? If so, the caption might look a little odd in HTML CSS.

**Comment by opoudjis** [comment]
Please review instance of example in 5.6.4.

It does look bad, but I don't want to change the ISO-based presentation of examples in the Metanorma stack. Suggestions welcome.

[17-069.html.zip](https://github.com/riboseinc/metanorma-ogc/files/2691726/17-069.html.zip)

**Comment by ronaldtse** [comment]
It looks quite weird now:

![screen shot 2018-12-19 at 11 31 28 am](https://user-images.githubusercontent.com/11865/50197525-695f5d00-0382-11e9-9bc3-e526787a6c20.png)

Can we make the rendered structure more reasonable, like this? I never liked using a table for EXAMPLEs.

![screen shot 2018-12-19 at 11 36 42 am](https://user-images.githubusercontent.com/11865/50197545-7aa86980-0382-11e9-820a-f5fbbd9d029b.png)

```html
<div class="example">
  <p class="figuretitle" style="font-weight: 600;">
    EXAMPLE: URL of the OpenAPI definition
  </p>
  <div class="example_body" style="padding-left: 2em;">
    <p id="_bfe1900d-bb06-49a5-a89b-6c131fcdfa2b" class="">
      If the OpenAPI Server Object looks like this:
    </p>
    <p id="_9e387384-be36-4c96-bca6-6a29d5f5a8b3" class="Sourcecode">
      servers:<br>
      &nbsp;&nbsp;-&nbsp;url:&nbsp;https://dev.example.org/<br>
      &nbsp;&nbsp;&nbsp;&nbsp;description:&nbsp;Development&nbsp;server<br>
      &nbsp;&nbsp;-&nbsp;url:&nbsp;https://data.example.org/<br>
      &nbsp;&nbsp;&nbsp;&nbsp;description:&nbsp;Production&nbsp;server
    </p>
    <p id="_498ffbba-d976-4b37-823c-203a9751d869" class="">
      The path “/mypath” in the OpenAPI definition of a WFS would be the URL <tt><a href="https://data.example.org/mypath">https://data.example.org/mypath</a></tt> for the production server.
    </p>
  </div>
</div>
```

**Comment by opoudjis** [comment]
Do you want this changed just for OGC, or in general? I thought this rendering was ISO's.

**Comment by ronaldtse** [comment]
In ISO Word the rendering style of a table has no borders. In ISO HTML it is our own style. 

So I’d say we should change the Example design for all the styles we control, I.e. all non ISO-Word styles.

**Comment by opoudjis** [comment]
Reenabled the old div rendering of examples in isodoc, and permitting either table or div rendering of examples. Only Word ISO will use the table rendering instead of the div rendering.

**Comment by opoudjis** [comment]
Changing all HTML css (but for the ISO and GB compliant modes) to follow the recommendation above.
