### ISSUE TITLE
Convert some sample OGC documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#2]
Testbed: https://github.com/opengeospatial/D012-MapML_Engineering_Report

Standard: https://github.com/opengeospatial/WFS_FES

**Comment by ronaldtse** [comment]
OGC TC Policies and procedures (all done)

* Repo: https://github.com/riboseinc/ogc-tcpnp
* Rendered: https://riboseinc.github.io/ogc-tcpnp/

Maybe we just need one more repo/doc.

**Comment by ronaldtse** [comment]
Candidate (already in AsciiDoc): https://github.com/ogcscotts/eo-wcs

Make a new repo for it please.

**Comment by opoudjis** [comment]
Is this still required? And if so, could you get someone else to do it?

**Comment by opoudjis** [comment]
@ronaldtse: So I'll do https://github.com/opengeospatial/WFS_FES ?

**Comment by opoudjis** [comment]
Done as https://github.com/riboseinc/ogc-wfs
