### ISSUE TITLE
Machine-readable requirement example

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#20]
In WFS 3 there is this requirement block:

```
Requirement 2
/req/core/root-success

A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.

The content of that response SHALL be based upon the OpenAPI 3.0 schema root.yaml and include at least links to the following resources:

* /api (relation type ‘service’)
* /conformance (relation type ‘conformance’)
* /collections (relation type ‘data’)
```

Is the following a good example of the textual representation?

```adoc
[requirement,label="/req/core/root-success",subject="endpoint",obligation="shall"]
====

[description]
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.

[routine,run="CoreRoot"]
----
CoreRoot(success): HttpResponse
if (success)
  recommendation(label: success-response)
end
----

[requirement,label="success-response"]
--

[description]
---
The content of that response SHALL be based upon the provided OpenAPI 3.0 schema and include at least links to the following resources:

* `/api` (relation type "service")
* `/conformance` (relation type "conformance")
* `/collections` (relation type "data")
---

[specification,type="oapi30"]
======
'/':
  get:
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/root'
            properties:
              type: array
              items:
                $ref: '#/components/schemas/link'
              match:
                - href: '/api'
                  rel: service
                - href: '/conformance'
                  rel: conformance
                - href: '/collections'
                  rel: data
          text/html:
            schema:
              type: string
======
--

====
```

**Comment by opoudjis** [comment]
routine is machine-readable validation code (though code and maths can also be requirements)

(I think validation and requirements should be marked up separately, not conflated as code (`routine`).)

The specification is the machine-readable counterpart to the description, and is in a specified DSL

requirement code in this instance is a hook, that will need to be supplied by the implementer. Should be tagged as an import if it is a hook.

**Comment by opoudjis** [comment]
I do not regard 

````
[requirement,label="success-response"]
--
````

as adequate: I simply don't think it is clear, or extensible. If it is to be a hook, let it be tagged as an import, and let it be an explicit code reference, not a label, which appears to be language specific.

As already pointed out, the obligation is not required, because we differentiate requirements, recommendations and permissions at tag level.

I would counterpropose the following, though I am vague on how all of this is meant to work:

````
[requirement,label="/req/core/root-success",subject="endpoint"]
====

[description]
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.

[validation,lang="CoreRoot"]
----
CoreRoot(success): HttpResponse
if (success)
  recommendation(label: success-response)
end
----

[import,lang="CoreRoot"]
--
success-response()
--

[description]
---
The content of that response SHALL be based upon the provided OpenAPI 3.0 schema and include at least links to the following resources:

* `/api` (relation type "service")
* `/conformance` (relation type "conformance")
* `/collections` (relation type "data")
---

[specification,type="oapi30"]
======
'/':
  get:
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/root'
            properties:
              type: array
              items:
                $ref: '#/components/schemas/link'
              match:
                - href: '/api'
                  rel: service
                - href: '/conformance'
                  rel: conformance
                - href: '/collections'
                  rel: data
          text/html:
            schema:
              type: string
======
--

====
````

**Comment by opoudjis** [comment]
From https://github.com/riboseinc/metanorma-nist/issues/7:

* The course to be pursued is 3: we still encode machine-readable requirements and textual requirements separately.
* Any unwrapped content in the requirement body is considered to be the requirement description.
* Open blocks are used to tag explicit requirement subparts, such as measurement targets. Targets can be in a language, for machine-readability, or they can be left untagged, in which case they are human-readable; the language "text" is also deemed human-readable.
* Requirement subparts are all by default included in output, whether machine-readable or not. They are excluded if tagged with the attribute "suppress".
* There will be provision for extracting .req files, although I presume each requirement will need to be a separate file.
* I do not yet understand what you mean by nested requirements. The example you have given is in fact a cross-referenced requirement, and it properly requires a Metanorma xref (which will be resolved within Metanorma; it is not clear whether it will be resolved within a .req document.)

**Comment by opoudjis** [comment]
From your sample requirements, I have found that you want import as an attribute to denote the label of an imported/nested requirement. I am renaming it "inherit", so it does not collide with "import" as denoting a code stub.

**Comment by opoudjis** [comment]
XML renderings of Sample machine readable requirements ready to upload to metanorma-mrr-samples, but you have not authorised me to! So attaching here as zip file.

[metanorma-mrr-samples.zip](https://github.com/riboseinc/metanorma-ogc/files/2801102/metanorma-mrr-samples.zip)

**Comment by ronaldtse** [comment]
@opoudjis what does this mean?
> I have found that you want import as an attribute to denote the label of an imported/nested requirement. I am renaming it "inherit", so it does not collide with "import" as denoting a code stub.

**Comment by opoudjis** [comment]
Name collision:

* inherit X: a requirement inherits from requirement X, and is a subclass of it
* import X: a reference to sourcecode which will be imported from elsewhere

**Comment by ronaldtse** [comment]
> As already pointed out, the obligation is not required, because we differentiate requirements, recommendations and permissions at tag level.

OK. But there may be more than one "obligation" of a requirement. We could support them on the tag level, but we want to make customization/extensions easy (for us).

> I think the description should _not_ be marked up: it should be all content of the requirement which is not in a labelled block. That is to make it easier to mark up requirements; a requirement without any internal markup should be resolvable to a text-based description.

The description of a requirement must:

* Be a part of the requirement.
* Support richer text.

Imagine a system that lists out requirements but want to look at what the requirement means. For example, https://nvd.nist.gov/download/800-53/800-53-controls.xml . It looks something like this:

```xml
    <ns3:control>
        <control-class>Technical</control-class>
        <family>Access Control</family>
        <number>AC-1</number>
        <title>Access Control Policy and Procedures</title>
        <priority>P1</priority>
        <description>
            <ns2:div>
                <ns2:p class="align_left">The organization develops, disseminates, and reviews/updates [<ns2:em>Assignment: organization-defined frequency</ns2:em>]:</ns2:p>
                <ns2:ol>
                    <ns2:li>A formal, documented access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and</ns2:li>
                    <ns2:li>Formal, documented procedures to facilitate the implementation of the access control policy and associated access controls.</ns2:li>
                </ns2:ol>
            </ns2:div>
        </description>
        <supplemental-guidance>
            <ns2:div>
                <ns2:p class="align_left">This control is intended to produce the policy and procedures that are required for the effective implementation of selected security controls and control enhancements in the access control family. The policy and procedures are consistent with applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance. Existing organizational policies and procedures may make the need for additional specific policies and procedures unnecessary. The access control policy can be included as part of the general information security policy for the organization. Access control procedures can be developed for the security program in general and for a particular information system, when required. The organizational risk management strategy is a key factor in the development of the access control policy. Related control: PM-9.</ns2:p>
            </ns2:div>
        </supplemental-guidance>
        <references>
            <reference href="http://csrc.nist.gov/publications/nistpubs/800-100/SP800-100-Mar07-2007.pdf">NIST 800-100</reference>
            <reference href="http://csrc.nist.gov/publications/nistpubs/800-12/handbook.pdf">NIST 800-12</reference>
        </references>
    </ns3:control>
```

> I do not see the reason for differentiating between `run` and `type` attributes.

The point was to differentiate a specification vs a piece of code that can be run as validation. 

For example, let's say we have a requirements document for a web service.

I can provide all the following at the same time:
. Specification: a spec in Open API syntax. (that can be run by an external validation tool)
. Specification: description of the specification
. Example: a (or more) piece of Ruby code that can be run to test (e.g. rspec) to validate 1 input vs 1 output
. Validation: code or validation description

How do we structure this?

> The course to be pursued is 3: we still encode machine-readable requirements and textual requirements separately.

Yes but they need to be the same "requirement" if they are about the same actual requirement.

> There will be provision for extracting .req files, although I presume each requirement will need to be a separate file.

Good call.

> I do not yet understand what you mean by nested requirements. The example you have given is in fact a cross-referenced requirement, and it properly requires a Metanorma xref (which will be resolved within Metanorma; it is not clear whether it will be resolved within a .req document.)

I think the point is we can have clauses and subclauses, and therefore there are requirements and sub-requirements. We just need to support that.

For example, you can have a "control set" vs a "control". As long as we can model this, I'm happy.

**Comment by ronaldtse** [comment]
@opoudjis have a look at https://nvd.nist.gov/download/800-53/800-53-controls.xml .

Do we want to support this data model for requirements? I think it is a good reference.

e.g.
```xml
    <ns3:control>
        <control-class>Technical</control-class>
        <family>System and Communications Protection</family>
        <number>SC-26</number>
        <title>Honeypots</title>
        <priority>P0</priority>
        <description>
            <ns2:div>
                <ns2:p class="align_left">The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.</ns2:p>
            </ns2:div>
        </description>
        <supplemental-guidance>
            <ns2:div>
                <ns2:p class="align_left">None.</ns2:p>
            </ns2:div>
        </supplemental-guidance>
        <control-enhancements>
            <control-enhancement sequence="1">
                <description>
                    <ns2:div>
                        <ns2:p class="align_left">The information system includes components that proactively seek to identify web-based malicious code.</ns2:p>
                    </ns2:div>
                </description>
                <supplemental-guidance>
                    <ns2:div>
                        <ns2:p class="align_left">Devices that actively seek out web-based malicious code by posing as clients are referred to as client honeypots or honey clients.</ns2:p>
                    </ns2:div>
                </supplemental-guidance>
            </control-enhancement>
        </control-enhancements>
    </ns3:control>
```

**Comment by opoudjis** [comment]
You have two long meandering discussions above, which I am going to break up here.

1. Obligations.

> OK. But there may be more than one "obligation" of a requirement. We could support them on the tag level, but we want to make customization/extensions easy (for us).

... I would rather keep requirements, recommendations, permissions completely separate at the tag level, since they are treated as completely separate assets in documents. Maybe if multiple obligations materialise I can add an override attribute with multiple values that allows that kind of vagueness about obligations, and treat "requirement" as a generic category in limited circumstances; but that really sounds like an edge case, and I'm not going to implement it until I see it: it is confusing.

*Will not fix.*

**Comment by opoudjis** [comment]
2. Descriptions with rich text:

> I think the description should not be marked up: it should be all content of the requirement which is not in a labelled block. That is to make it easier to mark up requirements; a requirement without any internal markup should be resolvable to a text-based description.
The description of a requirement must:

> * Be a part of the requirement.
> * Support richer text.

Both of which are met by the tagging as I have created it, and I see no earthly reason why I would need to introduce explicit tags around descriptions, when what I have implemented works fine.

Your requirement from the example above is that descriptions include paragraphs, ordered lists, italics, and paragraph alignment. No problem:

````
.Generic Structure for Permutation Testing
[requirement,type="pseudocode",label="/iid-testing/permutation-test/"]
====

[align=left]
The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.

The organization develops, disseminates, and reviews/updates [_Assignment: organization-defined frequency_]

. A formal, documented access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
. Formal, documented procedures to facilitate the implementation of the access control policy and associated access controls.


[verification,type="pseudo-fortress"]
--
[source,lang="DecideIID"]
----
import FisherYatesShuffle, TestStatistic
----
--

====
````

Rendered into XML as:

````
<requirement id="_e5872aac-8537-4512-a4fe-a4a37db46133"><label>/iid-testing/permutation-test/</label><description><p align="left" id="_b63dd7ab-6265-45d8-9fe5-5596d77e1daa">The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.</p>
<p id="_dfb92894-4b56-435b-89ee-7b9d496526e2">The organization develops, disseminates, and reviews/updates [<em>Assignment: organization-defined frequency</em>]</p>
<ol id="_df866cc8-b377-4d9c-a512-5cd310f4e240" type="arabic">
  <li>
    <p id="_ab60580e-e1e2-4098-b4d9-ad4cde932bf1">A formal, documented access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and</p>
  </li>
  <li>
    <p id="_8f408b6a-600d-4e23-951e-3712f11740fa">Formal, documented procedures to facilitate the implementation of the access control policy and associated access controls.</p>
  </li>
</ol>
</description><verification exclude="false" type="pseudo-fortress"><sourcecode id="_73f30284-185b-45f3-92dd-72fea0ad0e02">import FisherYatesShuffle, TestStatistic</sourcecode>
</verification></requirement>
````

*Nothing further for to do here*

**Comment by opoudjis** [comment]
3. Validation vs Specification

>> I do not see the reason for differentiating between run and type attributes.
>The point was to differentiate a specification vs a piece of code that can be run as validation.

> For example, let's say we have a requirements document for a web service.

> I can provide all the following at the same time:
> . Specification: a spec in Open API syntax. (that can be run by an external validation tool)
> . Specification: description of the specification
> . Example: a (or more) piece of Ruby code that can be run to test (e.g. rspec) to validate 1 input vs 1 output
> . Validation: code or validation description

> How do we structure this?

* _Specification: a spec in Open API syntax. (that can be run by an external validation tool):_
 
````
[specification]
--
[source]
----
sourcecode
----
--
````

Will become `<specification><sourcecode>`

_Specification: description of the specification_

Text within requirement that is not otherwise wrapped in an open block: will become `<description>`.

> . Example: a (or more) piece of Ruby code that can be run to test (e.g. rspec) to validate 1 input vs 1 output
> . Validation: code or validation description

I do not understand the distinction you are making between the example, *which is used for validation*, and the validation code. The latter, which is a general description of validation, would be tagged as `[verification]`, and will become `<verification>`, optionally containing `<sourcecode>` blocks.

The former is... well, I don't know what it is. But if you have a semantic distinction you want to make between them, it is not at the attribute level of "run" vs "type", which makes no sense to me: it is at the level of container. And if the code is not there for the purposes of verification, I do not know what it is there for. Onus is on you to explain this better, or point to some prior art explaining the difference.

*Pending clarification from Ronald*

**Comment by opoudjis** [comment]
4. Separation of machine readable and textual requirements

>> The course to be pursued is 3: we still encode machine-readable requirements and textual requirements separately.

> Yes but they need to be the same "requirement" if they are about the same actual requirement.

They will be. A single `[requirement]` container will contain, as separate open text blocks, specifications (`[specification]`) which may be machine readable (sourcecode), and which may be suppressed from document output (`%suppress` attribute); and human-readable text as descriptions (untagged text).

*Nothing further to do here*

**Comment by opoudjis** [comment]
5. Extraction of requirements

> There will be provision for extracting .req files, although I presume each requirement will need to be a separate file.

New issue: https://github.com/riboseinc/metanorma/issues/39

**Comment by opoudjis** [comment]
6. Nested requirements

>> I do not yet understand what you mean by nested requirements. The example you have given is in fact a cross-referenced requirement, and it properly requires a Metanorma xref (which will be resolved within Metanorma; it is not clear whether it will be resolved within a .req document.)

> I think the point is we can have clauses and subclauses, and therefore there are requirements and sub-requirements. We just need to support that.

> For example, you can have a "control set" vs a "control". As long as we can model this, I'm happy.

Of course, this is just like figures and subfigures: the containing requirement is not meant to have any content of its own.

Since examples in Asciidoc can be nested, there is no problem with marking up nested requirements:

````
.Generic Structure for Permutation Testing
[requirement,type="pseudocode",label="/iid-testing/permutation-test/"]
====

[requirement,type="pseudocode",label="/iid-testing/permutation-test/1"]
=====
[align=left]
The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.

The organization develops, disseminates, and reviews/updates [_Assignment: organization-defined frequency_]

. A formal, documented access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
. Formal, documented procedures to facilitate the implementation of the access control policy and associated access controls.
=====


[requirement,type="pseudocode",label="/iid-testing/permutation-test/2"]
=====
[verification,type="pseudo-fortress"]
--
[source,lang="DecideIID"]
----
import FisherYatesShuffle, TestStatistic
----
--
======

====
````

Renders as:

````
<requirement id="_b8918432-2b37-450b-be30-a7a901e2a813"><label>/iid-testing/permutation-test/</label><requirement id="_18e15a05-0e29-4211-a46a-8e7b22a5b2a6"><label>/iid-testing/permutation-test/1</label><description><p align="left" id="_05539d33-8742-40a1-9d11-480bc8d77e1e">The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.</p>
<p id="_1227eca4-67ef-4ab5-b795-cbeed93fb8ff">The organization develops, disseminates, and reviews/updates [<em>Assignment: organization-defined frequency</em>]</p>
<ol id="_a8ad6037-3e92-4c18-975c-55a1e6129b63" type="arabic">
  <li>
    <p id="_dd86b206-dbcd-4156-b7bd-cd6d1b5013b4">A formal, documented access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and</p>
  </li>
  <li>
    <p id="_dfbd090d-2828-4ff1-a2e4-9ba05b02d415">Formal, documented procedures to facilitate the implementation of the access control policy and associated access controls.</p>
  </li>
</ol></description></requirement>
<requirement id="_df73feaa-f470-4e86-8127-021a98d7344b"><label>/iid-testing/permutation-test/2</label><verification exclude="false" type="pseudo-fortress"><sourcecode id="_a62a4bcc-165f-4a25-9877-becc047c6e2b">import FisherYatesShuffle, TestStatistic</sourcecode>
</verification><description>
<example id="_3c17c129-1d6d-4b1c-862a-4f23f8651529">
  <p id="_35663507-a8dc-4434-8f24-87839e0a1dc5"/>
</example></description></requirement></requirement>
````

*Nothing further to do here*

**Comment by opoudjis** [comment]
7. As just ranted on message, I do not have a data model for NIST SP 800 53, I have some tags whose definition I do not know. What I can guess is completely idiosyncratic to security, and I am not interested in domain-specific modelling.

Taking the tags we have defined so far for Requirements:

* Control-Class: xxx
* Family: xxxx
* Number: requirement/label
* Title: requirement/title (which I've just realised I had not implemented: implementing)
* Priority: xxx
* Description: requirement/description
* Supplemental Guidance: xxxx
* Control Enhancements: xxxx

I am not going to add control classes, families, or priorities as tags to the model, because they are idiosyncratic. I am instead going to add key-value pairs to requirement metadata, where the key as well as the value is open-ended, because the number of classifications people can come up with for requirements is open-ended. So:

* Control-Class: /requirement/classification[@type = "control-class"]
* Family: /requirement/classification[@type = "family"]
* Priority: /requirement/classification[@type = "priority"]

I'm not impressed by control enhancements or supplemental guidance either: far from a "good reference", I think this is too vague to be useful. 

Supplemental guidance is defined in SP 800 53 as "Statements used to provide additional explanatory information for security controls or security control enhancements." These are mere notes, and I would not dignify them with more than /requirement/description/note (that's Metanorma Notes).

Control Enhancements are some sort of supplement of the original security control; these are arguably merely nested requirements: requirement/requirement.

**Comment by opoudjis** [comment]
3. The clarification provided by @ronaldtse is: an Example is a unit test, or code that tests a single feature or input or output; Verification code is a test suite that comprehensively tests a module.

That is not a semantic distinction, since both are verifications; they are only distinctions of scope of what they apply to. I am inclined not to make the distinction machine readable. All sorts of intermediate scopes of validation can be devised (single parameter vs single routine? routine vs module? module vs package? package vs organisational policy?), and it is pointless to come up with a controlled vocabulary, let alone a tagset, to differentiate them. They will both be verification, and I will add a type attribute to verification.

**Comment by opoudjis** [comment]
7. An XSLT is, I guess, feasible, but I'm not going to do it yet. But this is the Metanorma equivalent of the foregoing:

````
<requirement>
  <classification>
    <tag>control-class</tag>
    <value>Technical</value>
  </classification>
  <classification>
    <tag>family</tag>
    <value>System and Communications Protection</value>
  </classification>
  <classification>
    <tag>priority</tag>
    <value>P0</value>
  </classification>
  <label>SC-26</label>
  <title>Honeypots</title>
  <description>
    <p align="left">The information system includes components specifically designed to be the target of malicious attacks for the purpose of detecting, deflecting, and analyzing such attacks.</p>
    <note>None</note>
  </description>
  <requirement>
    <label>1</label>
    <description>
      <p align="left">The information system includes components that proactively seek to identify web-based malicious code.</p>
    </description>
  </requirement>
  <requirement>
    <label>1</label>
    <description>
      <p align="left">The information system includes components that proactively seek to identify web-based malicious code.</p>
      <note><p align="left">Devices that actively seek out web-based malicious code by posing as clients are referred to as client honeypots or honey clients.</p></note>
    </description>
  </requirement>
</requirement>      
````

**Comment by ronaldtse** [comment]
> 1. Obligations.
> Maybe if multiple obligations materialise I can add an override attribute with multiple values that allows that kind of vagueness about obligations, and treat "requirement" as a generic category in limited circumstances; but that really sounds like an edge case, and I'm not going to implement it until I see it: it is confusing.

OK.

**Comment by ronaldtse** [comment]
> 2. Descriptions with rich text:

I noticed that there is a `<description>` tag that separates it from the requirement. Good enough. Thanks.

**Comment by ronaldtse** [comment]
> 3. Validation vs Specification

Clarification: "validation" are the audit rules. "specification" is the specification on what has to be done. It is true that a "full validation" = checking the "full specification", but life isn't always that way. Hence we need to make a distinction between them.

We should be able to place "description" (i.e. rich text) and "sourcecode" in both. For example, I can place multiple `<sourcecode>` pieces inside validation as audit rules (within `<validation>`). The same for `<specification>`.

And there could be multiple of them -- multiple validation rules and multiple specifications.

If we can do this it's all good.

**Comment by ronaldtse** [comment]
> 4. Separation of machine readable and textual requirements

All good.

> 5. Extraction of requirements

All good.

> 6. Nested requirements

There is an empty `<example>` block in the example, can we get rid of that? 

```xml
<example id="_3c17c129-1d6d-4b1c-862a-4f23f8651529">
  <p id="_35663507-a8dc-4434-8f24-87839e0a1dc5"/>
</example>
```

Notice that we need two "types" of `<examples>` in this sort of markup:

* `<example>` in `<description>`, which is a example of the requirement or of its description.
* `<example>` in the machine-readable portions such as `<validation>`, which is a example of the rule specified.


> That is not a semantic distinction, since both are verifications; they are only distinctions of scope of what they apply to. I am inclined not to make the distinction machine readable. All sorts of intermediate scopes of validation can be devised (single parameter vs single routine? routine vs module? module vs package? package vs organisational policy?), and it is pointless to come up with a controlled vocabulary, let alone a tagset, to differentiate them. They will both be verification, and all requirement subparts already permit type attributes; so that would be <verification type="unit"> vs <verification type="comprehensive">.

Agree. This can be an arbitrary separation. The solution is fine.

> 7. An XSLT is, I guess, feasible, but I'm not going to do it yet. But this is the Metanorma equivalent of the foregoing:

This looks good to go!

**Comment by opoudjis** [comment]
>> 1. Obligations.
>> Maybe if multiple obligations materialise I can add an override attribute with multiple values that allows that kind of vagueness about obligations, and treat "requirement" as a generic category in limited circumstances; but that really sounds like an edge case, and I'm not going to implement it until I see it: it is confusing.

Changed my mind: I implemented it.

**Comment by opoudjis** [comment]
>> 3. Validation vs Specification

> Clarification: "validation" are the audit rules. "specification" is the specification on what has to be done. It is true that a "full validation" = checking the "full specification", but life isn't always that way. Hence we need to make a distinction between them.

Sure, and the distinction between validation and specification is already being made. Type on validation allows us to differentiate unit test from full spec, for example.

> We should be able to place "description" (i.e. rich text) and "sourcecode" in both. For example, I can place multiple `<sourcecode>` pieces inside validation as audit rules (within `<validation>`). The same for `<specification>`.

Yes, that is the case. Everything that is meant to be machine readable is meant to be in sourcecode; and every requirement subpart can contain both rich text and sourcecode.

> And there could be multiple of them -- multiple validation rules and multiple specifications.

Yes, there is an arbitrary number of intermixed requirement subparts.

**Comment by opoudjis** [comment]
>> 6. Nested requirements

> There is an empty `<example>` block in the example, can we get rid of that? 

Fixed, markup error.

> Notice that we need two "types" of `<examples>` in this sort of markup:

> * `<example>` in `<description>`, which is a example of the requirement or of its description.
> * `<example>` in the machine-readable portions such as `<validation>`, which is a example of the rule specified.

But the markup in Asciidoctor to leads to the two is the same. That's in order.

I think we're good.

**Comment by ronaldtse** [comment]
> But the markup in Asciidoctor to leads to the two is the same. That's in order.

The markup is the same but in different contexts :wink:
