### ISSUE TITLE
Broken stylesheet: EXAMPLE

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#22]
As shown.
<img width="538" alt="screen shot 2019-01-25 at 10 01 32 am" src="https://user-images.githubusercontent.com/11865/51735630-334f8000-2088-11e9-97cd-b50c804cf595.png">

**Comment by ronaldtse** [comment]
Note and other admonitions.

<img width="780" alt="screen shot 2019-01-25 at 10 01 58 am" src="https://user-images.githubusercontent.com/11865/51735660-43675f80-2088-11e9-9b2f-846615999dad.png">

**Comment by opoudjis** [comment]
Could you be more explicit about what the issues are?

**Comment by opoudjis** [comment]
Your example rendering is table-based. Make sure you bundle update: it is meant to inherit div based rendering from isodoc.

**Comment by ronaldtse** [comment]
NOTE. In metanorma-ogc-style:

<img width="558" alt="screen shot 2019-01-25 at 12 09 38 pm" src="https://user-images.githubusercontent.com/11865/51742462-1de35180-209a-11e9-89f4-a68e0c53c13b.png">

In the latest bundle, the yellow box is gone.

**Comment by opoudjis** [comment]
I will get to these tonight, but it will be late tonight.

**Comment by opoudjis** [comment]
Note rendering debugged.

**Comment by opoudjis** [comment]
Example rendering debugged.
