### ISSUE TITLE
Word templates for OGC documents 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#3]
Not that we should use them, since they are not very pretty. Placed here to infer their structures.

[OGC_Standard_Document_Template_10-176r8.docx](https://github.com/riboseinc/metanorma-ogc/files/2602597/OGC_Standard_Document_Template_10-176r8.docx)

[OGC_Implementation_Specification_template_building_on_OWS_Common.docx](https://github.com/riboseinc/metanorma-ogc/files/2602599/OGC_Implementation_Specification_template_building_on_OWS_Common.docx)

**Comment by opoudjis** [comment]
Thank you. So we will be committing to DOC as an output format; wasn't clear whether they were actively using it. We're likely to do a custom one?
