### ISSUE TITLE
Update document-type and document-stage according to README

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#5]
The README has been updated with the document-types and document-stages from https://github.com/riboseinc/metanorma-model-ogc/ .

This task is to:

1. Update the gem to support those; and also
2. Update the colors used for those document types/stages. See how it's done in metanorma-csd. Extra colors can be retrieved using https://coolors.co and entering the current colors.

**Comment by opoudjis** [comment]
Done
