### ISSUE TITLE
Display OGC-specific items on HTML/Word output

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc#6]
"Warning" for policy documents (http://docs.opengeospatial.org/pol/05-020r25/05-020r25.html)

> Warning
> This document is an OGC Policies and Procedures Document. The document is subject to change based on membership requirements and motions. Please note that the OGC “Policies Related to OGC Standards” should be also be read. [http://www.opengeospatial.org/ogc/policies/directives]

> Document stage:	Approved for public release
> Document subtype:	
> Document language:	English

> Submission Date: 2017-01-30
> Approval Date: 2017-06-06
> Publication Date: 2017-07-17
> External identifier of this OGC® document: : http://www.opengis.net/doc/tcpnp/25.0
> URL for this OGC® document: http://docs.opengeospatial.org/pol/05-020r25/05-020r25.html
> Internal reference number of this OGC® document: 05-020r25

> Additional Formats (informative):           

We need links to other formats from the HTML version. (this is also useful for CSD)

> Previous Version (informative):      html

If we can add a URL to be linked from it?

**Comment by opoudjis** [comment]
The "Document stage..." etc stuff is in the template, and I'm allowing it for all document types.

**Comment by opoudjis** [comment]
Propagated urls to metadata in isodoc.
